### ISSUE TITLE
Issue with Braintree

### ISSUE THREAD

**Issue by davekedar** [smarkets/react-native-paypal#1]
`In file included from /Users/kedardave/QualPros/node_modules/react-native-paypal/ios/RNPaypal.m:2:
/Users/kedardave/QualPros/node_modules/react-native-paypal/ios/RNPaypal.h:8:9: fatal error: 'BraintreeCore.h' file not found
#import "BraintreeCore.h"`

Getting the above error. Please help

Dependancies:
"react-native-paypal": "github:smarkets/react-native-paypal"

**Comment by riso** [comment]
Hi. did you run step #3 (`[iOS] Add pod 'Braintree' ...`) of readme? 

We don't bundle the Braintree SDK so that you're free to pick the library version that you need, but to do so you need cocoapods setup and add the Braintree library to your build.

If you're not using cocoapods you can add it by following the guide [here](https://guides.cocoapods.org/using/using-cocoapods).

Also, dependencies can be updated to `"react-native-paypal": "^2.0.0"` now. I'll update the readme.

**Comment by davekedar** [comment]
I have inserted `# Includes Cards and PayPal
pod 'Braintree'` in pod file, what else I have to do?

**Comment by davekedar** [comment]
Solved thanks

**Comment by riso** [comment]
Good to hear!

**Comment by charles4201** [comment]
> Solved thanks

Hello @davekedar, how did you solve the problem ? Could you please share with us ? 
Thank you !
