### ISSUE TITLE
Error requesting one time payment - "Merchant account not found"

### ISSUE THREAD

**Issue by dmamaril** [smarkets/react-native-paypal#10]
Hi,

Unsure how to proceed... it's likely a braintree issue, but I just want to make sure I'm covering my bases. I've triple checked my merchantId, publicKey and privateKey and ensured that they're 100% correct, however I'm receiving a `merchant not found` error still.

<img width="1189" alt="Screen Shot 2019-03-21 at 10 56 44 PM" src="https://user-images.githubusercontent.com/5885732/54803554-2df85700-4c2d-11e9-8f0f-cd81bcd66407.png">

**Braintree setup**
```
const gateway = braintree.connect({
    environment: braintree.Environment.Sandbox,
    merchantId: process.env.BRAINTREE_MERCHANT_ID,
    publicKey: process.env.BRAINTREE_PUBLIC_KEY,
    privateKey: process.env.BRAINTREE_PRIVATE_KEY
});
```

**createToken method**
```
    public createToken(request: Request, h: ResponseToolkit): Promise<string> {
        return new Promise((resolve, reject) => {
            this.gateway.clientToken.generate({}, (err, response) => {
                if (err) {
                    reject(err.message);
                } else if (!response.success) {
                    reject(response.message);
                } else {
                    resolve(response.clientToken);
                }
            });
        });
    }
```

**Click handler in UI**
```
        requestOneTimePayment(
            token,
            {
                amount: '5', // required
                // any PayPal supported currency (see here: https://developer.paypal.com/docs/integration/direct/rest/currency-codes/#paypal-account-payments)
                currency: 'GBP',
                // any PayPal supported locale (see here: https://braintree.github.io/braintree_ios/Classes/BTPayPalRequest.html#/c:objc(cs)BTPayPalRequest(py)localeCode)
                localeCode: 'en_GB',
                shippingAddressRequired: false,
                userAction: 'commit', // display 'Pay Now' on the PayPal review page
                // one of 'authorize', 'sale', 'order'. defaults to 'authorize'. see details here: https://developer.paypal.com/docs/api/payments/v1/#payment-create-request-body
                intent: 'authorize',
            }
        )
```

Any help would be greatly appreciated.

**Comment by riso** [comment]
Hey, sorry for the late reply and thanks for the detailed report. Your setup seems correct. Googling your issue seems to point at a misconfiguration of your paypal merchant account. I double checked our config and under https://developer.paypal.com/developer/applications/ you should see a section named 'Express Checkout via Braintree SDK - Sandbox Accounts' where your sandbox credentials are. As for merchant ID it should be in https://www.paypal.com/businessprofile/settings .. 

Ultimately though I think that the best thing you can do is get in touch with PayPal support as I think they would be best suited to help.

**Comment by image7** [comment]
I am facing the same issue. May i know how you solved this?

**Comment by ShaBax** [comment]
I think the problem is with the token you are using. Try to print the error you are getting you will get more info about the problem. 

In my case, it was the token (merchant not found). Try to use the token from this URL [Create Token](https://braintree-sample-merchant.herokuapp.com/client_token)

If you don't get any error by using this token then the problem is with your token, It means your Braintree account is not connected with your PayPal account. 

The solution is to link PayPal with your Braintree account  [How to link ](https://help.paperform.co/en/articles/2072845-how-to-connect-braintree-your-paperform-account-and-paypal)

**Comment by nafplann** [comment]
I was into this.. this solves the problem. [https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/server-side/node/](Paypal Integration)

**Comment by trimitrtechnologies** [comment]
For all users who still struggling to solve this issue follow the below steps:

- Logged in paypal
- Navigate to https://developer.paypal.com/developer/applications/
- Click on App Name in my case it was "Default Application"
- Copy Client Id and Secret
- Now log in https://sandbox.braintreegateway.com/
- Click on Processing
- You will see Payment Method section
- Turn on Paypal option if its already not, then click on link just down to toggle
- Enter Client id and secret you copied above

**Comment by riso** [comment]
Thanks for that :)

**Comment by alapanerao** [comment]
@trimitrtechnologies Thanks a lot for the solution. https://github.com/smarkets/react-native-paypal/issues/10#issuecomment-635281813

@riso can you please add this steps in ReadMe in setup guide ?
