### ISSUE TITLE
ERROR: Unable to resolve dependency for ':react-native-paypal@debug/compileClasspath'

### ISSUE THREAD

**Issue by mighty-nyaina** [smarkets/react-native-paypal#62]
Hi

I'm getting this issue on trying to install the library on android.

<img width="1024" alt="Screen Shot 2020-11-12 at 10 54 43" src="https://user-images.githubusercontent.com/15805563/98911515-c1069480-24d5-11eb-9642-9cf8be4c969d.png">

Here is my main build.gradle

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath 'com.google.gms:google-services:4.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual moduxle build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url 'https://maven.google.com' }
        maven { url "https://www.jitpack.io" }
    }
}
`

My app dependencies:

"dependencies": {
"react": "16.8.3",
"react-native": "0.59.9",
"react-native-paypal": "^3.1.1"
}

Can you help me out on this ?
Thanks

**Comment by nzankich** [comment]
@mighty-nyaina 
You should try and check the example app to see differences from your files

https://github.com/smarkets/react-native-paypal/blob/master/paypalExample/android/build.gradle
https://github.com/smarkets/react-native-paypal/blob/master/paypalExample/package.json

A couple of things to check:
1. Your react native version is over a year old and it might be worth updating
2. Your gradle build tools is out of date as well.  you may need to bump it

I would start with the build tools because that will be an easier fix

**Comment by nzankich** [comment]
Try out my suggestions and tag me if you're still seeing issues and I can reopen
